# Detect target platform, not host platform.
# CMAKE_SYSTEM_NAME / CMAKE_SYSTEM_PROCESSOR describe target.
# CMAKE_HOST_* describe build host.

set(_KRYSTALLIC_TARGET_PROCESSOR "${CMAKE_SYSTEM_PROCESSOR}")

if(CMAKE_GENERATOR_PLATFORM)
    set(_KRYSTALLIC_TARGET_PROCESSOR "${CMAKE_GENERATOR_PLATFORM}")
endif()

string(TOLOWER "${_KRYSTALLIC_TARGET_PROCESSOR}" _KRYSTALLIC_TARGET_PROCESSOR_LOWER)

set(KRYSTALLIC_OS_DEFINE "KRYSTALLIC_OS_UNKNOWN")
set(KRYSTALLIC_ARCH_DEFINE "KRYSTALLIC_ARCH_UNKNOWN")

if(CMAKE_SYSTEM_NAME STREQUAL "Android")

    set(KRYSTALLIC_OS_DEFINE "KRYSTALLIC_OS_ANDROID")

    if(ANDROID_ABI STREQUAL "arm64-v8a")
        set(KRYSTALLIC_PLATFORM "AndroidArm64")
        set(KRYSTALLIC_PLATFORM_DEFINE "KRYSTALLIC_PLATFORM_ANDROID_ARM64")
        set(KRYSTALLIC_ARCH_DEFINE "KRYSTALLIC_ARCH_ARMv8")

    elseif(ANDROID_ABI STREQUAL "armeabi-v7a")
        set(KRYSTALLIC_PLATFORM "AndroidArm7")
        set(KRYSTALLIC_PLATFORM_DEFINE "KRYSTALLIC_PLATFORM_ANDROID_ARM7")
        set(KRYSTALLIC_ARCH_DEFINE "KRYSTALLIC_ARCH_ARMv7")

    elseif(ANDROID_ABI STREQUAL "x86_64")
        set(KRYSTALLIC_PLATFORM "AndroidX64")
        set(KRYSTALLIC_PLATFORM_DEFINE "KRYSTALLIC_PLATFORM_ANDROID_X64")
        set(KRYSTALLIC_ARCH_DEFINE "KRYSTALLIC_ARCH_X64")

    elseif(ANDROID_ABI STREQUAL "x86")
        set(KRYSTALLIC_PLATFORM "AndroidX86")
        set(KRYSTALLIC_PLATFORM_DEFINE "KRYSTALLIC_PLATFORM_ANDROID_X86")
        set(KRYSTALLIC_ARCH_DEFINE "KRYSTALLIC_ARCH_X86")

    else()
        set(KRYSTALLIC_PLATFORM "Android")
        set(KRYSTALLIC_PLATFORM_DEFINE "KRYSTALLIC_PLATFORM_ANDROID")
    endif()

elseif(CMAKE_SYSTEM_NAME STREQUAL "Windows")

    set(KRYSTALLIC_OS_DEFINE "KRYSTALLIC_OS_WINNT")

    if(_KRYSTALLIC_TARGET_PROCESSOR_LOWER MATCHES "^(arm64|aarch64)$")
        set(KRYSTALLIC_PLATFORM "WinArm64")
        set(KRYSTALLIC_PLATFORM_DEFINE "KRYSTALLIC_PLATFORM_WINARM64")
        set(KRYSTALLIC_ARCH_DEFINE "KRYSTALLIC_ARCH_ARM64")

    elseif(_KRYSTALLIC_TARGET_PROCESSOR_LOWER MATCHES "^(amd64|x86_64|x64)$")
        set(KRYSTALLIC_PLATFORM "Win64")
        set(KRYSTALLIC_PLATFORM_DEFINE "KRYSTALLIC_PLATFORM_WIN64")
        set(KRYSTALLIC_ARCH_DEFINE "KRYSTALLIC_ARCH_X64")

    elseif(_KRYSTALLIC_TARGET_PROCESSOR_LOWER MATCHES "^(x86|i386|i686)$")
        set(KRYSTALLIC_PLATFORM "Win32")
        set(KRYSTALLIC_PLATFORM_DEFINE "KRYSTALLIC_PLATFORM_WIN32")
        set(KRYSTALLIC_ARCH_DEFINE "KRYSTALLIC_ARCH_X86")

    elseif(CMAKE_SIZEOF_VOID_P EQUAL 8)
        set(KRYSTALLIC_PLATFORM "Win64")
        set(KRYSTALLIC_PLATFORM_DEFINE "KRYSTALLIC_PLATFORM_WIN64")
        set(KRYSTALLIC_ARCH_DEFINE "KRYSTALLIC_ARCH_X64")

    else()
        set(KRYSTALLIC_PLATFORM "Win32")
        set(KRYSTALLIC_PLATFORM_DEFINE "KRYSTALLIC_PLATFORM_WIN32")
        set(KRYSTALLIC_ARCH_DEFINE "KRYSTALLIC_ARCH_X86")
    endif()

elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux")

    set(KRYSTALLIC_OS_DEFINE "KRYSTALLIC_OS_LINUX")

    if(_KRYSTALLIC_TARGET_PROCESSOR_LOWER MATCHES "^(arm64|aarch64)$")
        set(KRYSTALLIC_PLATFORM "LinuxArm64")
        set(KRYSTALLIC_PLATFORM_DEFINE "KRYSTALLIC_PLATFORM_LINUXARM64")
        set(KRYSTALLIC_ARCH_DEFINE "KRYSTALLIC_ARCH_ARM64")

    elseif(_KRYSTALLIC_TARGET_PROCESSOR_LOWER MATCHES "^(armv8|arm64-v8a)$")
        set(KRYSTALLIC_PLATFORM "LinuxArm64")
        set(KRYSTALLIC_PLATFORM_DEFINE "KRYSTALLIC_PLATFORM_LINUXARM64")
        set(KRYSTALLIC_ARCH_DEFINE "KRYSTALLIC_ARCH_ARMv8")

    elseif(_KRYSTALLIC_TARGET_PROCESSOR_LOWER MATCHES "^(armv7|armv7l|armhf)$")
        set(KRYSTALLIC_PLATFORM "LinuxArm7")
        set(KRYSTALLIC_PLATFORM_DEFINE "KRYSTALLIC_PLATFORM_LINUXARM7")
        set(KRYSTALLIC_ARCH_DEFINE "KRYSTALLIC_ARCH_ARMv7")

    elseif(_KRYSTALLIC_TARGET_PROCESSOR_LOWER MATCHES "^(x86_64|amd64|x64)$")
        set(KRYSTALLIC_PLATFORM "Linux64")
        set(KRYSTALLIC_PLATFORM_DEFINE "KRYSTALLIC_PLATFORM_LINUX64")
        set(KRYSTALLIC_ARCH_DEFINE "KRYSTALLIC_ARCH_X64")

    elseif(_KRYSTALLIC_TARGET_PROCESSOR_LOWER MATCHES "^(x86|i386|i686)$")
        set(KRYSTALLIC_PLATFORM "Linux32")
        set(KRYSTALLIC_PLATFORM_DEFINE "KRYSTALLIC_PLATFORM_LINUX32")
        set(KRYSTALLIC_ARCH_DEFINE "KRYSTALLIC_ARCH_X86")

    elseif(CMAKE_SIZEOF_VOID_P EQUAL 8)
        set(KRYSTALLIC_PLATFORM "Linux64")
        set(KRYSTALLIC_PLATFORM_DEFINE "KRYSTALLIC_PLATFORM_LINUX64")
        set(KRYSTALLIC_ARCH_DEFINE "KRYSTALLIC_ARCH_X64")

    else()
        set(KRYSTALLIC_PLATFORM "Linux32")
        set(KRYSTALLIC_PLATFORM_DEFINE "KRYSTALLIC_PLATFORM_LINUX32")
        set(KRYSTALLIC_ARCH_DEFINE "KRYSTALLIC_ARCH_X86")
    endif()

else()

    set(KRYSTALLIC_PLATFORM "Unknown")
    set(KRYSTALLIC_PLATFORM_DEFINE "KRYSTALLIC_PLATFORM_UNKNOWN")
    set(KRYSTALLIC_OS_DEFINE "KRYSTALLIC_OS_UNKNOWN")
    set(KRYSTALLIC_ARCH_DEFINE "KRYSTALLIC_ARCH_UNKNOWN")

endif()

# Utils are host tools, not target tools.
# During cross-compilation we still need host binaries, not target binaries.

set(_KRYSTALLIC_HOST_PROCESSOR "${CMAKE_HOST_SYSTEM_PROCESSOR}")
string(TOLOWER "${_KRYSTALLIC_HOST_PROCESSOR}" _KRYSTALLIC_HOST_PROCESSOR_LOWER)

if(CMAKE_HOST_WIN32)

    if(_KRYSTALLIC_HOST_PROCESSOR_LOWER MATCHES "^(arm64|aarch64)$")
        set(KRYSTALLIC_HOST_UTILS_PLATFORM "winarm64")
    elseif(_KRYSTALLIC_HOST_PROCESSOR_LOWER MATCHES "^(amd64|x86_64|x64)$")
        set(KRYSTALLIC_HOST_UTILS_PLATFORM "win64")
    else()
        set(KRYSTALLIC_HOST_UTILS_PLATFORM "win32")
    endif()

elseif(CMAKE_HOST_SYSTEM_NAME STREQUAL "Linux")

    if(_KRYSTALLIC_HOST_PROCESSOR_LOWER MATCHES "^(arm64|aarch64)$")
        set(KRYSTALLIC_HOST_UTILS_PLATFORM "linuxarm64")
    elseif(_KRYSTALLIC_HOST_PROCESSOR_LOWER MATCHES "^(x86_64|amd64|x64)$")
        set(KRYSTALLIC_HOST_UTILS_PLATFORM "linux64")
    else()
        set(KRYSTALLIC_HOST_UTILS_PLATFORM "linux32")
    endif()

else()

    set(KRYSTALLIC_HOST_UTILS_PLATFORM "")

endif()

set(KRYSTALLIC_UTILS_DIR "${CMAKE_SOURCE_DIR}/utils/${KRYSTALLIC_HOST_UTILS_PLATFORM}")


message(STATUS "CMAKE_SYSTEM_NAME=${CMAKE_SYSTEM_NAME}")
message(STATUS "CMAKE_SYSTEM_PROCESSOR=${CMAKE_SYSTEM_PROCESSOR}")
message(STATUS "CMAKE_SIZEOF_VOID_P=${CMAKE_SIZEOF_VOID_P}")
message(STATUS "KRYSTALLIC_PLATFORM=${KRYSTALLIC_PLATFORM}")
message(STATUS "KRYSTALLIC_PLATFORM_DEFINE=${KRYSTALLIC_PLATFORM_DEFINE}")
message(STATUS "KRYSTALLIC_OS_DEFINE=${KRYSTALLIC_OS_DEFINE}")
message(STATUS "KRYSTALLIC_ARCH_DEFINE=${KRYSTALLIC_ARCH_DEFINE}")
message(STATUS "KRYSTALLIC_HOST_UTILS_PLATFORM=${KRYSTALLIC_HOST_UTILS_PLATFORM}")
message(STATUS "_KRYSTALLIC_HOST_PROCESSOR=${_KRYSTALLIC_HOST_PROCESSOR}")
message(STATUS "_KRYSTALLIC_HOST_PROCESSOR_LOWER=${_KRYSTALLIC_HOST_PROCESSOR_LOWER}")


unset(_KRYSTALLIC_HOST_PROCESSOR)
unset(_KRYSTALLIC_HOST_PROCESSOR_LOWER)